version: "3.9"
services:
  postgres:
    image: "postgres:latest"
    ports:
      - 5432:5432
    #volumes:
    #  - ./data/postgres:/var/lib/postgresql/data  
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=cache
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  igovium:
    build: 
      context: .
      dockerfile: Dockerfile
    #image: igovium:latest
    ports:
      - 9988:9988
      - 50051:50051
    volumes:
      - ./compose-conf.yaml:/compose-conf.yaml
    environment:
      - IGOVIUM_CONFIG=/compose-conf.yaml
    depends_on:
      - postgres
      - redis
    restart: on-failure